### ISSUE TITLE
Update for newer GHC releases.

### ISSUE THREAD

**Issue by lemmih** [danieldk/digest-pure#1]
Hiya,

I cannot build the package with ghc-7.8.2 due to the constraint on array. Would you mind relaxing this constraint?

**Comment by danieldk** [comment]
I'll have a look at it! (I still have to install 7.8)

**Comment by lemmih** [comment]
Btw, I found a bug/misfeature in Data.ByteString.Lazy that made CRC32 way slower than it should be. Adler is also affected. When it is fixed, both your implementations should perform much closer to the C versions.

https://github.com/haskell/bytestring/issues/20

**Comment by danieldk** [comment]
Thanks! I uploaded version 0.0.3 with the relaxed constraint to Hackage. I'll update the benchmarks when a new bytestring is out.
